<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="tileset" tilewidth="16" tileheight="16" tilecount="256" columns="8">
 <image source="tileset.png" width="128" height="128"/>
 <tile id="0" type="Actor"/>
 <tile id="1" type="Actor"/>
 <tile id="2" type="Actor"/>
 <tile id="3" type="Actor"/>
 <tile id="4" type="Actor"/>
 <tile id="5" type="Actor"/>
 <tile id="6" type="Actor"/>
 <tile id="7" type="Actor"/>
 <tile id="8" type="Actor"/>
 <tile id="9" type="Actor"/>
 <tile id="10" type="Actor"/>
 <tile id="11" type="Actor"/>
 <tile id="12" type="Actor"/>
 <tile id="13" type="Actor"/>
 <tile id="14" type="Actor"/>
 <tile id="15" type="Actor"/>
 <tile id="16" type="Actor"/>
 <tile id="17" type="Actor"/>
 <tile id="18" type="Actor"/>
 <tile id="19" type="Actor"/>
 <tile id="20" type="Actor"/>
 <tile id="21" type="Actor"/>
 <tile id="22" type="Actor"/>
 <tile id="23" type="Actor"/>
 <tile id="24" type="Actor"/>
 <tile id="25" type="Actor"/>
 <tile id="26" type="Actor"/>
 <tile id="27" type="Actor"/>
 <tile id="28" type="Actor"/>
 <tile id="29" type="Actor"/>
 <tile id="30" type="Actor"/>
 <tile id="31" type="Actor"/>
 <tile id="32" type="Actor"/>
 <tile id="33" type="Actor"/>
 <tile id="34" type="Actor"/>
 <tile id="35" type="Actor"/>
 <tile id="36" type="Actor"/>
 <tile id="37" type="Actor"/>
 <tile id="38" type="Actor"/>
 <tile id="39" type="Actor"/>
 <tile id="40" type="Actor"/>
 <tile id="41" type="Actor"/>
 <tile id="42" type="Actor"/>
 <tile id="43" type="Actor"/>
 <tile id="44" type="Actor"/>
 <tile id="45" type="Actor"/>
 <tile id="46" type="Actor"/>
 <tile id="47" type="Actor"/>
 <tile id="48" type="Actor"/>
 <tile id="49" type="Actor"/>
 <tile id="50" type="Actor"/>
 <tile id="51" type="Actor"/>
 <tile id="52" type="Actor"/>
 <tile id="53" type="Actor"/>
 <tile id="54" type="Actor"/>
 <tile id="55" type="Actor"/>
 <tile id="56" type="Actor"/>
 <tile id="57" type="Actor"/>
 <tile id="58" type="Actor"/>
 <tile id="59" type="Actor"/>
 <tile id="60" type="Actor"/>
 <tile id="61" type="Actor"/>
 <tile id="62" type="Actor"/>
 <tile id="63" type="Actor"/>
</tileset>
